# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=15, unique=True)),
                ('user_pass', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_details', models.TextField(max_length=255)),
                ('item_creation_dt', models.DateTimeField(auto_now_add=True)),
                ('item_update_dt', models.DateTimeField(auto_now=True)),
                ('item_priority', models.IntegerField(default=1)),
                ('item_url', models.URLField(unique=True)),
                ('item_price', models.FloatField()),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapi_v1.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='LikedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_dt', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapi_v1.Items')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=17, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=15, unique=True)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_creation_dt', models.DateTimeField(auto_now_add=True)),
                ('user_modify_dt', models.DateTimeField(null=True)),
                ('user_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='likeditems',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapi_v1.Users'),
        ),
    ]
